import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import foody from "../assets/foody.png";
import smartquery from "../assets/smartquery.png";

const stack = ["Python", "Flask", "AWS SES / EC2 / S3", "Gemini AI", "PostgreSQL", "Jinja2", "PyMuPDF"];

function Projects() {
  const [detailsOpen, setDetailsOpen] = useState(false);
  const projects = [{ title: "Foody", description: "A food ordering platform concept with a user-friendly interface and real-time tracking direction.", image: foody, href: "https://muhammad-khawar-riaz-abbasi.github.io/Foody/" }, { title: "SmartQuery", description: "An intelligent query management concept designed to simplify complex business operations.", image: smartquery, href: "#" }];
  return <section id="projects"><div className="section-wrap"><p className="eyebrow">04 — Selected work</p><h2 className="section-title">Systems that do more than look good.</h2><motion.article className="featured-project" initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><div className="featured-copy"><span className="project-label">Featured project · NGO automation</span><h3>NHSD Email<br /><span>Marketing Engine</span></h3><p>Complete donor marketing pipeline: Discovery → AI Profiling → Segmentation → Personalised Email → AWS SES Delivery → Analytics.</p><p className="muted-small">Actively powers GlobalGiving, Benevity & Myriad USA fundraising campaigns for NHSD. Runs 24/7 on AWS EC2, reducing manual workload to zero.</p><div className="chip-row">{stack.map((item) => <motion.span whileHover={{ scale: 1.05 }} className="chip chip-dark" key={item}>{item}</motion.span>)}</div><button className="btn btn-light mt-7" onClick={() => setDetailsOpen((value) => !value)} aria-expanded={detailsOpen}>{detailsOpen ? "Hide details" : "View details"} <span>{detailsOpen ? "↑" : "↗"}</span></button><AnimatePresence>{detailsOpen && <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }} className="project-details"><p>The engine connects discovery, classification, routing, templating, delivery, and reporting into one repeatable workflow. It uses 25+ donor themes and Gemini-powered classification to turn raw discovery into relevant outreach.</p></motion.div>}</AnimatePresence></div><div className="architecture" aria-label="Marketing automation architecture diagram">{["Discovery", "AI profiling", "Audience routing", "Personalised email", "AWS SES", "Analytics"].map((step, index) => <React.Fragment key={step}><div className="architecture-step"><span>0{index + 1}</span>{step}</div>{index < 5 && <span className="architecture-arrow" aria-hidden="true">→</span>}</React.Fragment>)}</div></motion.article><div className="mt-20"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="eyebrow">Other projects</p><h3 className="mt-2 text-3xl font-bold tracking-tight">Earlier builds, still useful.</h3></div><span className="font-mono text-sm text-[var(--muted)]">02 projects</span></div><div className="project-grid">{projects.map((project, index) => <motion.article key={project.title} whileHover={{ y: -8 }} className="project-card"><img src={project.image} alt={`${project.title} project preview`} loading="lazy" /><div className="p-6"><span className="font-mono text-xs text-[var(--accent)]">0{index + 1} / project</span><h3 className="mt-3 text-2xl font-bold">{project.title}</h3><p className="mt-3 text-[var(--muted)]">{project.description}</p>{project.href !== "#" && <a className="project-link" href={project.href} target="_blank" rel="noreferrer">Explore project →</a>}</div></motion.article>)}</div></div></div></section>;
}

export default Projects;
